name: local
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.3.3
  # Animation or Routing Animation
  animations: ^2.0.7
  lottie: ^2.7.0

  # Graphics
  cached_network_image: ^3.3.0
  graphic: ^2.2.0  # Column Graph

  # Third Party Widgets
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  dropdown_search: ^5.0.6
  intl_phone_field: ^3.1.0
  percent_indicator: ^4.2.3

  # Http Request
  dio: ^5.1.2

  # Encryption
  encrypt: ^5.0.1

  # Functional Programming
  dartz: ^0.10.1

  # Development Utilities
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_launcher_icons: ^0.13.0

  # Form Validation
  formz: ^0.7.0

  # State Management
  flutter_bloc: ^8.1.3

  # Dependency Injection
  get_it: ^7.6.0

  # Push Notifications
  flutter_local_notifications: ^17.0.0

  # Fonts
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1

  # Image Handling
  image_cropper: ^5.0.0
  image_picker: ^1.0.2

  # Localization
  intl: ^0.18.1

  # Logging
  logger: ^2.0.2+1

  # Data Persistence
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # Location
  geolocator: ^11.0.0

  # Toast Messages
  fluttertoast: ^8.2.2

  # Calendar and Date Picker
  flutter_calendar_carousel: ^2.4.2
  flutter_datetime_picker: ^1.5.1

  # File Handling
  open_file: ^3.3.1
  file_picker: ^6.1.1
  shimmer: ^3.0.0
  readmore: ^2.2.0
  flutter_html: ^3.0.0-beta.2
  multi_select_flutter: ^4.1.3
  url_launcher: ^6.1.12
  visibility_detector: ^0.4.0+2
  image: ^4.1.3
  photo_view: ^0.14.0
  easy_stepper: ^0.8.2
  scroll_to_index: ^3.0.1
  barcode: ^2.2.4
  image_gallery_saver: ^2.0.3
  share_plus: ^7.2.1
  flutter_svg: ^2.0.9
  barcode_image: ^2.0.3
  path: ^1.8.3
  path_provider: ^2.1.1
  dash_chat_2: ^0.0.20
  speech_to_text: ^6.6.0
  http: ^1.2.1
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
   - assets/
  fonts:
    - family: popR
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: popSB
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: popB
      fonts:
        - asset: fonts/Poppins-Bold.ttf
